export const CORE_VERSION = 2;

export const ITEM_TYPES = ['watch','clock','jewellery','accessory','collectible','other'];
export const ITEM_PURPOSES = ['resale','personal','customer','donor','reference'];
export const ITEM_STATUSES = ['Incoming','Acquired','Researching','Preparing','On bench','Awaiting parts','Ready to list','Listed','Sold','Retained','Archived'];
export const WORK_TYPES = ['service','repair','inspection','cleaning','restoration','photography','listing'];
export const WORK_STATUSES = ['Planned','In progress','Waiting','Complete','Cancelled'];

const now=()=>new Date().toISOString();
const uid=prefix=>`${prefix}-${Math.random().toString(36).slice(2,9)}${Date.now().toString(36).slice(-4)}`;
const list=v=>Array.isArray(v)?v:[];
const text=v=>v==null?'':String(v);

export function blankCommercial(partial={}){return {purchasePrice:'',buyerPremium:'',postage:'',preparationCost:'',repairCost:'',partsCost:'',consumables:'',externalService:'',marketplaceFees:'',shippingToBuyer:'',otherCost:'',labourMinutes:'',labourRate:'',targetSale:'',minSale:'',actualSale:'',source:'',saleChannel:'Not listed',acquiredAt:'',listedAt:'',soldAt:'',...partial};}
export function blankIdentity(partial={}){return {maker:'',model:'',title:'',country:'',era:'',year:'',materials:'',marks:'',reference:'',serial:'',dimensions:'',weight:'',notes:'',...partial};}
export function blankWatchExtension(partial={}){return {passport:{},movement:{},timingHistory:[],publicPassport:{published:false,publicId:'',publishedAt:''},...partial,timingHistory:list(partial.timingHistory),publicPassport:{published:false,publicId:'',publishedAt:'',...(partial.publicPassport||{})}};}
export function createItem(partial={}){const createdAt=partial.createdAt||now(),type=ITEM_TYPES.includes(partial.type)?partial.type:'other',purpose=ITEM_PURPOSES.includes(partial.purpose)?partial.purpose:'resale';const item={id:partial.id||uid('item'),type,purpose,title:partial.title||'Untitled item',status:ITEM_STATUSES.includes(partial.status)?partial.status:'Acquired',identity:blankIdentity(partial.identity),condition:partial.condition||'',research:list(partial.research),mediaAssetIds:list(partial.mediaAssetIds),commercial:blankCommercial(partial.commercial),sale:partial.sale&&typeof partial.sale==='object'?partial.sale:{},workIds:list(partial.workIds),tags:list(partial.tags),notes:partial.notes||'',createdAt,updatedAt:partial.updatedAt||createdAt};if(type==='watch'||type==='clock')item.watch=blankWatchExtension(partial.watch);return item;}
export function createWork(partial={}){const createdAt=partial.createdAt||now();return {id:partial.id||uid('work'),itemId:text(partial.itemId),number:text(partial.number),type:WORK_TYPES.includes(partial.type)?partial.type:'inspection',title:partial.title||'Work',status:WORK_STATUSES.includes(partial.status)?partial.status:'Planned',diagnosis:partial.diagnosis||'',faults:list(partial.faults),diagnosticFaults:list(partial.diagnosticFaults),stages:list(partial.stages),measurements:list(partial.measurements),partIds:list(partial.partIds),labour:partial.labour&&typeof partial.labour==='object'?{minutes:'',rate:'',...(partial.labour||{})}:{minutes:'',rate:''},timingRuns:list(partial.timingRuns),repairPerformed:partial.repairPerformed||'',decision:partial.decision||'',finalQC:partial.finalQC&&typeof partial.finalQC==='object'?partial.finalQC:{},nextAction:partial.nextAction||'',blocker:partial.blocker||'',openedAt:partial.openedAt||createdAt.slice(0,10),completedAt:partial.completedAt||'',createdAt,updatedAt:partial.updatedAt||createdAt};}
export function createMediaAsset(partial={}){const createdAt=partial.createdAt||now();return {id:partial.id||uid('media'),itemId:text(partial.itemId),workId:text(partial.workId),category:partial.category||'workshop',source:partial.source||'',storageKey:partial.storageKey||'',url:partial.url||'',thumbnailUrl:partial.thumbnailUrl||'',originalName:partial.originalName||'',mimeType:partial.mimeType||'',bytes:Number(partial.bytes)||0,width:partial.width??null,height:partial.height??null,caption:partial.caption||'',evidenceNote:partial.evidenceNote||'',visibility:partial.visibility==='public'?'public':'private',isCover:!!partial.isCover,createdAt,updatedAt:partial.updatedAt||createdAt};}
export function createCoreState(partial={}){return {version:CORE_VERSION,currentItemId:partial.currentItemId||null,currentWorkId:partial.currentWorkId||null,items:list(partial.items),work:list(partial.work),mediaAssets:list(partial.mediaAssets),inventory:partial.inventory&&typeof partial.inventory==='object'?partial.inventory:{parts:[],tools:[],consumables:[],donors:[]},compatibilityEvidence:list(partial.compatibilityEvidence),incoming:list(partial.incoming),knowledge:list(partial.knowledge),settings:partial.settings&&typeof partial.settings==='object'?partial.settings:{},updatedAt:partial.updatedAt||now()};}
export function validateCoreState(state={}){const errors=[];if(state.version!==CORE_VERSION)errors.push('Unsupported core version');const itemIds=new Set();for(const item of list(state.items)){if(!item?.id||itemIds.has(item.id))errors.push(`Invalid or duplicate item id: ${item?.id||'(missing)'}`);itemIds.add(item?.id);}const workIds=new Set();for(const work of list(state.work)){if(!work?.id||workIds.has(work.id))errors.push(`Invalid or duplicate work id: ${work?.id||'(missing)'}`);workIds.add(work?.id);if(!itemIds.has(work?.itemId))errors.push(`Work ${work?.id||'(missing)'} references missing Item ${work?.itemId||'(missing)'}`);}for(const item of list(state.items))for(const workId of list(item.workIds))if(!workIds.has(workId))errors.push(`Item ${item.id} references missing Work ${workId}`);return {healthy:errors.length===0,errors};}
