import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const SUPABASE_URL="https://jdeqnboljrgrpnvkfthx.supabase.co";
const SUPABASE_KEY="sb_publishable_fWijlFfBeTw4Ku8EPkno7w_BgOARn0j";
const client=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const money=(v,c="AUD")=>{const n=Number(v);return Number.isFinite(n)&&v!==""?new Intl.NumberFormat("en-AU",{style:"currency",currency:c,maximumFractionDigits:0}).format(n):""};
const statusLabel=s=>s==="for_sale"?"For sale":s==="sold"?"Sold":s==="catalogue"?"Catalogue":"";
const images=row=>Array.isArray(row?.public_data?.images)?[...row.public_data.images].sort((a,b)=>(a.order??999)-(b.order??999)):[];
const cover=row=>images(row).find(x=>x?.role==="cover")?.url||images(row)[0]?.url||"";
const watchHref=slug=>location.hostname==="calibreco.com.au"||location.hostname==="www.calibreco.com.au"?`/watch/${encodeURIComponent(slug)}`:`watch.html?slug=${encodeURIComponent(slug)}`;
function card(row){const d=row.public_data||{},f=d.facts||{},img=cover(row),subtitle=[f.maker,f.model,f.year,f.calibre?`Cal. ${f.calibre}`:""].filter(Boolean).join(" · "),price=row.status==="for_sale"?money(d.price,d.currency||"AUD"):"";return `<a class="watch-card" href="${watchHref(row.slug)}"><div class="photo">${img?`<img src="${esc(img)}" alt="${esc(row.title)}">`:`<span>${esc((f.maker||row.title||"C").charAt(0))}</span>`}</div><div class="card-body"><div class="meta"><span>${esc(statusLabel(row.status))}</span><span>${esc(f.year||"")}</span></div><h2>${esc(row.title)}</h2><div class="desc">${esc(subtitle||d.description||"")}</div>${price?`<div class="price">${esc(price)}</div>`:""}</div></a>`;}
async function loadCatalogue(){const host=document.getElementById("catalogue");if(!host)return;const {data,error}=await client.from("calibre_public_watches").select("slug,status,title,public_data,published_at,updated_at").order("updated_at",{ascending:false});if(error){host.innerHTML=`<div class="empty">Catalogue unavailable.</div>`;return;}const rows=Array.isArray(data)?data:[],q=document.getElementById("q"),status=document.getElementById("status"),count=document.getElementById("count"),empty=document.getElementById("empty");function paint(){const needle=String(q.value||"").toLowerCase().trim(),st=status.value;const filtered=rows.filter(r=>{if(st!=="all"&&r.status!==st)return false;const d=r.public_data||{},f=d.facts||{},hay=[r.title,d.description,f.maker,f.model,f.year,f.calibre].join(" ").toLowerCase();return !needle||hay.includes(needle);});host.innerHTML=filtered.map(card).join("");count.textContent=`${filtered.length} watch${filtered.length===1?"":"es"}`;empty.hidden=filtered.length>0;}q.addEventListener("input",paint);status.addEventListener("change",paint);paint();}
function fact(label,value){return value?`<div class="fact"><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`:"";}
function gallery(row){const imgs=images(row);if(!imgs.length)return `<div class="passport-photo"><span>No public photograph</span></div>`;const hero=cover(row)||imgs[0].url;const thumbs=imgs.length>1?`<div class="passport-thumbs">${imgs.map((img,i)=>`<button type="button" class="passport-thumb${img.url===hero?" active":""}" data-image="${esc(img.url)}" aria-label="View photograph ${i+1}"><img src="${esc(img.url)}" alt=""></button>`).join("")}</div>`:"";return `<div class="passport-photo"><img id="passportHero" src="${esc(hero)}" alt=""></div>${thumbs}`;}
async function loadPassport(){const host=document.getElementById("passport");if(!host)return;const params=new URLSearchParams(location.search),slug=params.get("slug")||location.pathname.split("/").filter(Boolean).pop();if(!slug){host.innerHTML="<div class='empty'>No watch selected.</div>";return;}const {data,error}=await client.from("calibre_public_watches").select("slug,status,title,public_data,published_at,updated_at").eq("slug",slug).maybeSingle();if(error||!data){host.innerHTML="<div class='empty'>This watch is not publicly available.</div>";return;}const d=data.public_data||{},f=d.facts||{},price=data.status==="for_sale"?money(d.price,d.currency||"AUD"):"",caseText=[f.caseMaterial,f.caseStyle].filter(Boolean).join(" · "),dims=[f.width?`${f.width} mm wide`:"",f.length?`${f.length} mm long`:"",f.thickness?`${f.thickness} mm thick`:""].filter(Boolean).join(" · "),timing=f.timing?`${Number(f.timing.rateSecondsPerDay)>=0?"+":""}${f.timing.rateSecondsPerDay} s/day${f.timing.position?` · ${f.timing.position}`:""}`:"";document.title=`${data.title} - Calibre & Co.`;host.innerHTML=`<div class="passport-grid"><div>${gallery(data)}${f.serviceSummary?`<section class="section"><h3>Workshop record</h3><p>${esc(f.serviceSummary)}</p></section>`:""}</div><div><div class="eyebrow">WATCH PASSPORT</div><h1>${esc(data.title)}</h1><span class="status">${esc(statusLabel(data.status))}</span>${price?`<div class="price" style="font-size:1.15rem;margin:14px 0">${esc(price)}</div>`:""}${d.description?`<p class="lead">${esc(d.description)}</p>`:""}<div class="facts">${fact("Maker",f.maker)}${fact("Model",f.model)}${fact("Year",f.year)}${fact("Calibre",f.calibre)}${fact("Jewels",f.jewels)}${fact("Case",caseText)}${fact("Dimensions",dims)}${fact("Timing",timing)}</div><div class="passport-id">Calibre & Co. public record · ${esc(data.slug)}</div></div></div>`;host.querySelectorAll(".passport-thumb").forEach(btn=>btn.onclick=()=>{const hero=document.getElementById("passportHero");if(hero)hero.src=btn.dataset.image;host.querySelectorAll(".passport-thumb").forEach(x=>x.classList.toggle("active",x===btn));});}
loadCatalogue();loadPassport();